[env]
WINIT_X11_SCALE_FACTOR = "1.0"
COLORTERM = "truecolor"

[window]
decorations = "None"
decorations_theme_variant = "Dark"
resize_increments = true

[scrolling]
history = 10000
multiplier = 3

[cursor]
style = { shape = "Block", blinking = "On" }

[mouse]
hide_when_typing = true

[font]
# list available values: fc-list -f "%{family[0]}: %{style[0]}\n"
normal = { family = "SauceCodePro Nerd Font Mono", style = "Regular" }
size = 14
